version: '3.8'

services:
  ecosphere-db:
    image: postgres:15-alpine
    container_name: ecosphere_postgres
    environment:
      POSTGRES_USER: esg_admin
      POSTGRES_PASSWORD: esg_secure_password
      POSTGRES_DB: ecosphere_operational
    ports:
      - "5433:5432" # Avoids port conflict with local pgAdmin/Postgres on 5432
    volumes:
      - ecosphere_db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Automatically runs schema on startup
    restart: always

volumes:
  ecosphere_db_data:
    driver: local